/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataStructure.Questions;
import Main.Mainframe;
import javax.swing.JDialog;

/**
 *
 * @author zepingluo
 */
public class MCPanel extends javax.swing.JPanel {

    Mainframe frame;
    /**
     * Creates new form MCPanel
     */
    public MCPanel(Mainframe frame) {
        this.frame = frame;
        initComponents();
        load();
    }
    
    public void load()
    {
        A.setSelected(true);
        Easy.setSelected(true);
        questionNumLabel.setText("Question # "+(frame.numQuestion+1));
          
        Questions cur = frame.questionList.get(frame.numQuestion);
        choiceA.setText(cur.getChoices()[0]);
        choiceB.setText(cur.getChoices()[1]);
        choiceC.setText(cur.getChoices()[2]);
        choiceD.setText(cur.getChoices()[3]);
        stemArea.setText(cur.getStem());
        fileLabel.setText(cur.getImageFile());
        String answer =cur.getCorrectAnswer();
        
            if(answer.equalsIgnoreCase("A"))
            {
                A.setSelected(true);
                
            }
            
            if(answer.equalsIgnoreCase("B"))
            {
                B.setSelected(true);
                
            }
            
            if(answer.equalsIgnoreCase("C"))
            {
                C.setSelected(true);
                
            }
            
            if(answer.equalsIgnoreCase("D"))
            {
                D.setSelected(true);
                
            }
            
            
        
        
        if(cur.getDifficulty()==0)
        {
            Easy.setSelected(true);
            
        }
        if(cur.getDifficulty()==1)
        {
            Medium.setSelected(true);
        }
        if(cur.getDifficulty()==2)
        {
            Hard.setSelected(true);
        }
        
      
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        choiceA = new javax.swing.JTextField();
        choiceB = new javax.swing.JTextField();
        choiceC = new javax.swing.JTextField();
        choiceD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        stemArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Alabel = new javax.swing.JLabel();
        Blabel = new javax.swing.JLabel();
        Clabel = new javax.swing.JLabel();
        Dlabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        imageFileLabel = new javax.swing.JLabel();
        chooseFile = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        questionNumLabel = new javax.swing.JLabel();
        B = new javax.swing.JRadioButton();
        A = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        fileLabel = new javax.swing.JLabel();
        Easy = new javax.swing.JRadioButton();
        Medium = new javax.swing.JRadioButton();
        Hard = new javax.swing.JRadioButton();

        choiceB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceBActionPerformed(evt);
            }
        });

        stemArea.setColumns(20);
        stemArea.setRows(5);
        jScrollPane1.setViewportView(stemArea);

        jLabel1.setText("Enter Question below");

        Alabel.setText("Enter Option A");

        Blabel.setText("Enter Option B");

        Clabel.setText("Enter Option C");

        Dlabel.setText("Enter Option D");

        difficultyLabel.setText("difficulty");

        imageFileLabel.setText("Image File");

        chooseFile.setText("chooseFile");
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });

        saveButton.setText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(B);
        B.setText("B");

        buttonGroup2.add(A);
        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        buttonGroup2.add(C);
        C.setText("C");

        buttonGroup2.add(D);
        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        fileLabel.setText("jLabel2");

        buttonGroup1.add(Easy);
        Easy.setText("Easy");

        buttonGroup1.add(Medium);
        Medium.setText("Medium");

        buttonGroup1.add(Hard);
        Hard.setText("Hard");
        Hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageFileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseFile)
                                .addGap(26, 26, 26)
                                .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(difficultyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Easy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Medium)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                                .addComponent(saveButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(choiceA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Clabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Dlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(choiceD, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(choiceC)
                                        .addComponent(choiceB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Blabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Alabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B)
                            .addComponent(A)
                            .addComponent(C)
                            .addComponent(D)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(questionNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alabel)
                            .addComponent(choiceA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(choiceB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Blabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choiceC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clabel)
                    .addComponent(C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choiceD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dlabel)
                    .addComponent(D))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(difficultyLabel)
                    .addComponent(saveButton)
                    .addComponent(Easy)
                    .addComponent(Medium)
                    .addComponent(Hard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseFile)
                    .addComponent(imageFileLabel)
                    .addComponent(fileLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void choiceBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceBActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_choiceBActionPerformed

    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(frame, true);
        dialog.add(new openPicturePanel(frame));
        dialog.pack();
        dialog.setVisible(true);
        fileLabel.setText(frame.questionList.get(frame.numQuestion).getImageFile());
    }//GEN-LAST:event_chooseFileActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        A.setActionCommand("A");
        B.setActionCommand("B");
        C.setActionCommand("C");
        D.setActionCommand("D");
        String correctAnswer=buttonGroup2.getSelection().getActionCommand();
        
        
        String[] choices = {choiceA.getText(),choiceB.getText(),choiceC.getText(),choiceD.getText()};
        String stem=stemArea.getText();
        Easy.setActionCommand("0");
        Medium.setActionCommand("1");
        Hard.setActionCommand("2");
        String dif = buttonGroup1.getSelection().getActionCommand();
        int difficulty;
        if(dif.equals("1"))
        {
            difficulty=1;
        }
        else if(dif.equals("2"))
        {
            difficulty=2;
        }
        else
        {
            difficulty=0;
        }
        
        frame.questionList.get(frame.numQuestion).setQuestionInfo(stem, choices, correctAnswer, difficulty);
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DActionPerformed

    private void HardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JLabel Alabel;
    private javax.swing.JRadioButton B;
    private javax.swing.JLabel Blabel;
    private javax.swing.JRadioButton C;
    private javax.swing.JLabel Clabel;
    private javax.swing.JRadioButton D;
    private javax.swing.JLabel Dlabel;
    private javax.swing.JRadioButton Easy;
    private javax.swing.JRadioButton Hard;
    private javax.swing.JRadioButton Medium;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField choiceA;
    private javax.swing.JTextField choiceB;
    private javax.swing.JTextField choiceC;
    private javax.swing.JTextField choiceD;
    private javax.swing.JButton chooseFile;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JLabel imageFileLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel questionNumLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea stemArea;
    // End of variables declaration//GEN-END:variables
}
