/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataStructure.Questions;
import Main.Copy;
import Main.Mainframe;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author zepingluo
 */
public class openPicturePanel extends javax.swing.JPanel {

    Mainframe frame;
    int numQuestion;
    ArrayList<Questions> questionList;
    String folderPath;
    /**
     * Creates new form openPanel
     */
    public openPicturePanel(Mainframe frame) {
        initComponents();
        numQuestion= frame.numQuestion;
        questionList=frame.questionList;
        folderPath=frame.folderPath;
       }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();

        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        // TODO add your handling code here:
         if (evt.getActionCommand().equals("CancelSelection"))
        {
            ((JDialog) this.getTopLevelAncestor()).dispose();
        }
        else if (fileChooser.getSelectedFile().getAbsolutePath() == null)
        {
            
        }
        else
        {
            //record into question
            String filepath = fileChooser.getSelectedFile().getAbsolutePath();
           
            
            
            
               
             try {
                 System.out.println("openpic folder path:"+folderPath);
                 Copy.copyFile(new File(filepath), new File(folderPath+"/q"+(numQuestion+1)+".jpg"));
             } catch (IOException ex) {
                 Logger.getLogger(openPicturePanel.class.getName()).log(Level.SEVERE, null, ex);
             }
             questionList.get(numQuestion).setImageFile(folderPath+"/q"+(numQuestion+1)+".jpg");
             
        }
                ((JDialog) this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_fileChooserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables
}
